"""empty message

Revision ID: 596e8c1b8988
Revises: 64223ff09759
Create Date: 2025-05-11 08:19:35.943192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596e8c1b8988'
down_revision = '64223ff09759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
