"""add password_hash to users

Revision ID: 64223ff09759
Revises: 4019b50b07c6
Create Date: 2025-04-24 10:01:11.845987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64223ff09759'
down_revision = '4019b50b07c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
