"""update campaign model

Revision ID: 6d69432c2997
Revises: 596e8c1b8988
Create Date: 2025-05-17 03:48:47.581030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d69432c2997'
down_revision = '596e8c1b8988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_surveys',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.survey_id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'survey_id')
    )
    with op.batch_alter_table('campaign_participation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('survey_responses_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_survey_responses', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('required_survey_responses')

    with op.batch_alter_table('campaign_participation', schema=None) as batch_op:
        batch_op.drop_column('survey_responses_count')

    op.drop_table('campaign_surveys')
    # ### end Alembic commands ###
