"""remove user from incentives

Revision ID: bf5c1917e44d
Revises: 6d69432c2997
Create Date: 2025-05-22 06:58:14.392012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5c1917e44d'
down_revision = '6d69432c2997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incentives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('incentives_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'campaigns', ['campaign_id'], ['campaign_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incentives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('incentives_user_id_fkey', 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('campaign_id')

    # ### end Alembic commands ###
